### ISSUE TITLE
API for going from WrappedStream -> rustls::Session

### ISSUE THREAD

**Issue by alex** [ctz/hyper-rustls#11]
My specific goal is to go from `hyper::server::Request` to a client certificate.

I can get from `Request`  to `WrappedStream` with `request.ssl::<hyper_rustls::WrappedStream>().unwrap()`, and a `rustls::Session` has `get_peer_certificates`, so it seems the missing piece is `hyper_rustls::WrappedStream` -> `rustls::Session`.

**Comment by ctz** [comment]
Could you test if this does what you want? https://github.com/ctz/hyper-rustls/pull/12

**Comment by alex** [comment]
#12 fixes this!
