### ISSUE TITLE
'cannot access native cert store

### ISSUE THREAD

**Issue by Gdocal** [ctz/hyper-rustls#112]
Thread 'fetch' panicked at 'cannot access native cert store: Custom { kind: InvalidData, error: BadDER }', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-rustls-0.18.0\src\connector.rs:29

I got this issue when tried to run https://github.com/openethereum/openethereum client.
I use 
OS Name	Microsoft Windows 10 Pro
Version	10.0.18363 Build 18363

What can cause this issue? And how it can be solved?

**Comment by ctz** [comment]
It would be useful to know what the source of the offending certificates are -- please run certmgr.msc and try to identify them?

**Comment by ctz** [comment]
Actually, this is precisely the issue worked-around in 0.20. Please upgrade.

**Comment by Gdocal** [comment]
> It would be useful to know what the source of the offending certificates are -- please run certmgr.msc and try to identify them?

What I should look for here? 



> Actually, this is precisely the issue worked-around in 0.20. Please upgrade.

It is not my program (which use this lib), and as I understand it can't be easily  upgraded.
I want to find a root of problem which cause this issue and fix it manually..
The program which use this lib works ok on other PCs, just not in mine..
