### ISSUE TITLE
New release with tokio v1.0

### ISSUE THREAD

**Issue by benesch** [ctz/hyper-rustls#138]
Hey @ctz—quite keen to get a new release with the recent upgrade with the tokio v1.0/hyper v0.14 bump! One of the last two pieces to get a new release of Rusoto out. Thanks in advance!

**Comment by hannesdejager** [comment]
Would be kind yes. The only dependency that is blocking us upgrading to tokio 1.0/hyper 0.14 for libunftp

**Comment by ctz** [comment]
https://crates.io/crates/hyper-rustls/0.22.0 -- shout if you have any problems!

**Comment by hannesdejager** [comment]
Many thanks!
