### ISSUE TITLE
Semantic error

### ISSUE THREAD

**Issue by jy00464346** [ctz/hyper-rustls#23]
In the file lib. rs ,Lines 73 to 80 : 
```
fn promote_tls_error(&mut self) -> io::Result<()> {
    match self.tls_error.take() {
      Some(err) => {
        return Err(io::Error::new(io::ErrorKind::ConnectionAborted, err));
      },
      None => return Ok(())
    };
  }
```
is that correct? Should remove the ';'?

**Comment by lucab** [comment]
It is formally correct because both arms have explicit returns so nothing relies on the final result of expression evaluation. However, I agree it would be more idiomatic to drop both `return` and the `;` alltogether. I think clippy also highlights this nowadays.

**Comment by ctz** [comment]
This code was deleted in the recent merge.
