### ISSUE TITLE
HttpsConnector: expose a rustls ClientConfig builder

### ISSUE THREAD

**Issue by lucab** [ctz/hyper-rustls#27]
Capturing from https://github.com/ctz/hyper-rustls/pull/6#issuecomment-296398362:

> let people pass in a whole Arc<rustls::ClientConfig>, then they can do all the file IO and error handling outside TlsClient.

I would like to see such a feature as well. I'm a bit unsure about what is the expected signature here.

I was thinking about some simple `with_config(&cfg)`, however hyper-tls seems to have taken a different approach and now has a
```
fn from(args: (T, TlsConnector)) -> HttpsConnector<T>
```

@ctz should we have a similar `from() `here? Directly taking a `ClientSession` (I'm unsure about the hostname in the constructor)?

**Comment by sanmai-NL** [comment]
Question related to this. Is it in any way possible yet to make `HttpsConnector` accept a self-signed certificate?

**Comment by lucab** [comment]
It should be possible by adding the self-signed certificate to the rustls `ClientSession` root store. See the client example in https://github.com/ctz/hyper-rustls/pull/28 and try/check if it works for you.
