### ISSUE TITLE
HTTPS doesn't work with proxy

### ISSUE THREAD

**Issue by zaari** [ctz/hyper-rustls#3]
How do you use hyper-rustls with an http proxy? The following results an error.

```rust
let ssl = TlsClient::new();
let connector = HttpsConnector::new(ssl);
let proxy_config = ProxyConfig::new("http", host, port, connector, ssl);
let client = Client::with_proxy_config(proxy_config);
```

The error message is:

the trait bound `hyper_rustls::TlsClient: hyper::net::SslClient<hyper::net::HttpsStream<hyper_rustls::WrappedStream>>` is not satisfied

**Comment by ctz** [comment]
`connector` here gets you to the proxy, then `ssl` is used through the proxy to tunnel HTTPS requests. I've updated `examples/client.rs` to show this working.

**Comment by zaari** [comment]
That's a good example which solved my problem. Thank you.
