### ISSUE TITLE
Add example of server based on new Hyper API (>=0.11.7)

### ISSUE THREAD

**Issue by sanmai-NL** [ctz/hyper-rustls#36]
[The first parts](https://github.com/hyperium/hyper/blob/a453ea1064f7a151c67872cacc89cb51ca5ee682/tests/server.rs#L60-L99) of the new Hyper server API [came in v0.11.7](https://github.com/hyperium/hyper/blob/master/CHANGELOG.md#v0117-2017-11-14), i.e. [`server::Serve`](https://hyper.rs/hyper/master/hyper/server/struct.Serve.html) and [`Http::serve_connection`](https://hyper.rs/hyper/master/hyper/server/struct.Http.html#method.serve_connection).

I wonder how `hyper-rustls` fits with this. @P-E-Meunier explained in hyperium/hyper#1326 he is also looking for more control over the socket and transport without lots of complex code. Is somebody able to present an example here of combining `hyper-rustls` with the new server API?

**Comment by lucab** [comment]
@sanmai-NL you may want to have a look at https://github.com/ctz/hyper-rustls/pull/41/files#diff-bac3b8e7f9e4eb8c5c4f625b9ef7bd9b, which contains a hyper-0.12 server over tokio-rustls.

**Comment by sanmai-NL** [comment]
Yay! The current example code works fine with with `hyper` >= 0.12.
