### ISSUE TITLE
Align HttpsConnector with hyper-tls

### ISSUE THREAD

**Issue by kpcyrd** [ctz/hyper-rustls#39]
The HttpsConnector currently has a different signature from hyper-tls:

### [hyper-tls](https://docs.rs/hyper-tls/0.1.3/hyper_tls/struct.HttpsConnector.html)
```
impl HttpsConnector<HttpConnector>
```

### [hyper-rustls](https://docs.rs/hyper-rustls/0.12.0/hyper_rustls/struct.HttpsConnector.html)
```
impl HttpsConnector
```

It would be nice if I could provide my own [HttpConnector](https://docs.rs/hyper/0.11.22/hyper/client/struct.HttpConnector.html), also this would make it easier to switch them with a feature flag.

**Comment by kpcyrd** [comment]
@lucab Thanks! I've added a commit that removes more references to HttpConnector, you can pull it from here: https://github.com/kpcyrd/hyper-rustls/tree/ups/hyper-0.12

**Comment by lucab** [comment]
Ack, added to the PR.
