### ISSUE TITLE
hyper 0.12 support

### ISSUE THREAD

**Issue by kpcyrd** [ctz/hyper-rustls#40]
I'm currently having issues porting my code to hyper 0.12 and getting it to work with hyper-rustls again.

Currently I'm stuck here:
```
the trait `hyper::client::connect::Connect` is not implemented for `hyper_rustls::HttpsConnector`
```

I think a new release might be necessary. Thanks for building rustls and hyper-rustls! :)

**Comment by fdubois1** [comment]
@kpcyrd  : Did you find a way to do tls with hyper 0.12 ?

**Comment by kpcyrd** [comment]
@fdubois1 [hyper-tls][1] is able to use hyper 0.12, but I couldn't find a way to get it to work with rustls yet.

[1]: https://github.com/hyperium/hyper-tls/blob/master/examples/client.rs

**Comment by kpcyrd** [comment]
I've successfully ported my application to hyper 0.12 using hyper-rustls from your branch :)
