### ISSUE TITLE
Connector may panic

### ISSUE THREAD

**Issue by kpcyrd** [ctz/hyper-rustls#42]
It seems the unwrap in this line of the connector:
```rust
let dnsname = DNSNameRef::try_from_ascii_str(dst.host()).unwrap();
```
may panic if the url contains an IP instead of an host name. I can't get my patch to compile right now, so I'm leaving this as an issue instead. :)

**Comment by lucab** [comment]
Ouch. Indeed I forgot to remove the unwrap from my final PR. I think I have the half-working code for this somewhere locally, I'll finish and push it tomorrow.

**Comment by lucab** [comment]
It is up at https://github.com/ctz/hyper-rustls/pull/43
