### ISSUE TITLE
Cannot make HTTPS connection to www.googleapis.com as of v0.17.0

### ISSUE THREAD

**Issue by jbg** [ctz/hyper-rustls#77]
As of v0.17.0, I am unable to successfully make an HTTPS connection to www.googleapis.com. Using HTTP/2, I get a "connection closed" response (it seems the server drops the connection). Using HTTP/1.1, the connection hangs indefinitely.

There's a code snippet and debug logs here: https://gist.github.com/jbg/2b24ec191dac2bd0ad165d43efd50b11

Prior to the v0.17.0 release, we were using a local fork of hyper-rustls that I had updated to use the new rustls/tokio-rustls/etc releases, and had no issues. There's a small difference between the way v0.17.0 was updated to use the new tokio-rustls API, and the way I had updated our local fork.

With this patch applied to v0.17.0, I'm able to connect to www.googleapis.com over TLS successfully again:

https://github.com/ctz/hyper-rustls/compare/master...jbg:master?expand=1

**Comment by lucab** [comment]
Yes, I think I introduced a bug when porting to newer rustls. The CI here didn't catch it, but the reqwest one is complaining too: https://github.com/seanmonstar/reqwest/pull/593.

**Comment by lucab** [comment]
@jbg you are indeed right. Can you please post a PR with the fix?

**Comment by jbg** [comment]
PR: https://github.com/ctz/hyper-rustls/pull/78
