### ISSUE TITLE
Update rustls version to `0.5.8` to make it work with nightly compiler.

### ISSUE THREAD

**Issue by timgluz** [ctz/hyper-rustls#8]
Hi,

thanks for your library! I'm using it to get around of OpenSSL nightmares on different platforms.

I encountered a compiler error when i tried to compile my project with `nightly` rustc.
Error is caused by old version of [rustls](https://crates.io/crates/rustls), which is using unknown compiler feature `#[export_macro]`. That issue is now fixed in `0.5.8` . source: [https://github.com/ctz/rustls/issues/55](https://github.com/ctz/rustls/issues/55) 

Is it welcome to submit PR that upgrades just that dependency?
ps: I'm not in hurry and i can wait for next release.

**Comment by bruceadams** [comment]
@timgluz The dependency here on rustls is `rustls = "0.5.6"` which allows for higher minor versions, including `0.5.8`. Can you try doing `cargo update` in your project that uses `hyper-rustls`?

For what it's worth, my project https://github.com/bruceadams/wdsapi depends on `hyper-rustls` and my concrete use (where I have `Cargo.lock` checked into source control) is in https://github.com/bruceadams/wdscli, see https://github.com/bruceadams/wdscli/blob/master/Cargo.lock#L105:L112 which shows `rustls 0.5.8` as a dependency of `hyper-rustls`.

**Comment by timgluz** [comment]
Hi,

thanks. It worked.
