### ISSUE TITLE
invalid dnsname

### ISSUE THREAD

**Issue by IThawk** [ctz/hyper-rustls#84]
use this example:
Starting to serve on https://127.0.0.1:1337.
[!] Voluntary server halt due to client-connection error...
FAILED: run errorerror trying to connect: invalid dnsname

**Comment by IThawk** [comment]
let path = "D:\\workSpace\\myrust\\rust-demo\\web_tcp\\config\\sample.pem";
    let f = fs::File::open(path)
        .map_err(|e| error(format!("failed to open {}: {}", path, e)))?;
    let rds = io::BufReader::new(f);
    let mut ca = Some(rds);
    // Prepare the HTTPS connector.
    println!("读取证书完成");
    let https = match ca {
        Some(ref mut rd) => {
            // Build an HTTP connector which supports HTTPS too.
            let mut http = client::HttpConnector::new(4);
            http.enforce_http(false);
            // Build a TLS client, using the custom CA store for lookups.
            let mut tls = rustls::ClientConfig::new();
            tls.root_store
                .add_pem_file(rd)
                .map_err(|_| error("failed to load custom CA store".into()))?;
            // Join the above part into an HTTPS connector.
            hyper_rustls::HttpsConnector::from((http, tls))
        }
        // Default HTTPS connector.

        None => {
            println!("证书有问题!");
            hyper_rustls::HttpsConnector::new(4)
        }
    };

**Comment by ctz** [comment]
The destination must be a hostname, not an IP address. Connecting via an IP address isn't supported currently in the rustls or webpki crates.

**Comment by mcobzarenco** [comment]
This seem a pretty major limitation of `rustls` IMO :disappointed:

**Comment by ufoscout** [comment]
@ctz I guess this issue should be kept open to track the possible resolution of the problem.
In a project of my company, we had to move from rustls to openssl due to this. We would be happy to switch back to rustls when this is solved.

**Comment by lucab** [comment]
@ufoscout see https://github.com/ctz/hyper-rustls/issues/56.

**Comment by oxlade39** [comment]
I came across this when using rustls + hyper-rustls + hyper-proxy. I think I'm getting this error because the proxy is an IP address.

I'm not sure how to proceed here, it seems a fundamental blocker that the address must be a hostname. 
Why's this been closed?

**Comment by djc** [comment]
Because it is tracked in #56.

**Comment by oxlade39** [comment]
> Because it is tracked in #56.

Thank you. I didn't see that.
