### ISSUE TITLE
0.18 release on crates.io but not in git?

### ISSUE THREAD

**Issue by alex** [ctz/hyper-rustls#88]
crates.io has an 0.18 release issued a few minutes ago, but I don't see any changes for it in git.

**Comment by alex** [comment]
Err, ok, the tag is there now. Ignore me!

**Comment by ctz** [comment]
Yeah, I've just added a bit of release history to README.md to hopefully clear this up

**Comment by alex** [comment]
@ctz is there any chance of putting an 0.19 alpha on crates.io, so folks depending on that can clearly indicate that upgrading from 0.18-alpha => 0.18 isn't what they want? (Thanks!)

**Comment by ctz** [comment]
Yes, that's a fine idea. https://crates.io/crates/hyper-rustls/0.19.0-alpha.3
