### ISSUE TITLE
HTTP/2 server support

### ISSUE THREAD

**Issue by fluffysquirrels** [ctz/hyper-rustls#89]
I'm looking to serve HTTP/1.1 and HTTP/2 over TLS behind the same port with ALPN. Is that within scope for this crate or as an example in this crate?

**Comment by Darkspirit** [comment]
https://github.com/ctz/hyper-rustls/blob/master/examples/server.rs
Yes! In this example, hyper will automatically use HTTP/2 if a client starts talking HTTP/2, otherwise HTTP/1.1 will be used.

**Comment by fluffysquirrels** [comment]
That's a great feature.

I created a PR to mention HTTP/2 support.

**Comment by fluffysquirrels** [comment]
I don't think HTTP/2 works in the server example currently based on local testing with curl. I pushed a PR (https://github.com/ctz/hyper-rustls/pull/91) to configure ALPN, which fixes this.

**Comment by fluffysquirrels** [comment]
My PRs got merged so I'll close this now.
