### ISSUE TITLE
hyper-current: needs update for latest hyper master?

### ISSUE THREAD

**Issue by lucab** [ctz/hyper-rustls#9]
I was having a quick look at this crate and I *think* the hyper-current branch (for async hyper) may be a bit behind. `hyper::client::HttpsConnector` is not anymore there and I'm not sure how the whole thing has been re-arranged. Any hints / branch to a have a working async-hyper + rustls setup?

**Comment by ctz** [comment]
Yeah, I haven't been keeping up on this since the move to tokio. It could easily be that this crate becomes obsoleted by tokio-rustls.

**Comment by lucab** [comment]
I am a bit confused, as I don't see any Connect-like interface offered by tokio-rustls. Are you saying that future plans are to directly bridge hyper and tokio-rustls, or that I should look elsewhere right now?

**Comment by lucab** [comment]
Fixed by https://github.com/ctz/hyper-rustls/pull/22.
